# Generated by Django 2.1.7 on 2019-03-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointer', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('occupation', models.CharField(max_length=25)),
                ('is_child', models.BooleanField()),
                ('is_deceased', models.BooleanField()),
                ('birth_date', models.CharField(max_length=50)),
                ('birth_place', models.CharField(max_length=50)),
                ('death_date', models.CharField(max_length=50)),
                ('death_place', models.CharField(max_length=50)),
                ('burial_date', models.CharField(max_length=50)),
                ('burial_place', models.CharField(max_length=50)),
                ('last_change_date', models.DateField()),
                ('marriage_data', models.CharField(max_length=50)),
                ('children', models.ManyToManyField(related_name='_individual_children_+', to='mainapp.Individual')),
                ('parents', models.ManyToManyField(related_name='_individual_parents_+', to='mainapp.Individual')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(related_name='family', to='mainapp.Individual'),
        ),
    ]
