# Generated by Django 2.1.7 on 2019-02-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=25)),
                ('occupation', models.CharField(max_length=25)),
                ('is_individual', models.IntegerField()),
                ('is_child', models.IntegerField()),
                ('is_family', models.IntegerField()),
                ('is_deceased', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=25)),
                ('death_date', models.DateField()),
                ('death_place', models.CharField(max_length=25)),
                ('burial_date', models.DateField()),
                ('burial_place', models.CharField(max_length=25)),
                ('last_change_date', models.DateField()),
                ('marriage_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('root_element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapp.Element')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='children',
            field=models.ManyToManyField(related_name='_element_children_+', to='mainapp.Element'),
        ),
        migrations.AddField(
            model_name='element',
            name='parents',
            field=models.ManyToManyField(related_name='_element_parents_+', to='mainapp.Element'),
        ),
        migrations.AddField(
            model_name='element',
            name='spouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Element'),
        ),
    ]
