# Generated by Django 2.1.7 on 2019-03-02 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='individual',
            name='children',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='parents',
        ),
        migrations.AddField(
            model_name='relation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_accessor', to='mainapp.Individual'),
        ),
        migrations.AddField(
            model_name='relation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_accessor', to='mainapp.Individual'),
        ),
        migrations.AddField(
            model_name='individual',
            name='relations',
            field=models.ManyToManyField(to='mainapp.Relation'),
        ),
    ]
