# Generated by Django 2.1.7 on 2019-02-21 20:38

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='tree',
            name='root_element',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
    ]
